### ISSUE TITLE
 API account needs an internet address, no local ip?

### ISSUE THREAD

**Issue by gitgetgot** [FTLam11/Audio-Station-Scrobbler#1]
Hi and thank you for the greatly documented piece of software.

I'm stuck here:
https://github.com/FTLam11/Audio-Station-Scrobbler#create-api-account

`local_address_of_your_nas:3000`

so I tried to use a Callback URL like `192.168.1.1:3000`

but last.fm is complaining, I need to enter an "internetaddress". (no more info)

What now? 

What is the Port for? Is it the port of my DiskStation, or AudioStation, or maybe a NodeJS port?

**Comment by gitgetgot** [comment]
Darn, here is something to update the docs with :-) (for the dummies like me)

On the Last.fm API Creation page, you need to enter **HTTP** (even you DS is running HTTPS) as the protocol for your local DS IP address. Do not just enter the plain IP Address.

Port 3000 is the Listening Port of NodeJS. It is shown, when you have executed 'npm start'.

**Comment by FTLam11** [comment]
@gitgetgot Crap I totally didn't get any notifications about any of the issues you opened, I gotta sort that out. Anyways, I'll update the README. Thanks for opening this issue!
