### ISSUE TITLE
NodeJS needed after install?

### ISSUE THREAD

**Issue by gitgetgot** [FTLam11/Audio-Station-Scrobbler#5]
Can we safely deinstall the [NodeJS Package](https://github.com/FTLam11/Audio-Station-Scrobbler#system-requirements) after the Scrobbler Module is successfully installed and working, or do we need it for the Scrobbler Module to work?

**Comment by FTLam11** [comment]
The scrobbling module is a server written using NodeJS, therefore it is required.
